'use strict';

const fs = require('node:fs/promises');
const path = require('path');
const debug = require('debug')('WireGuard');
const crypto = require('node:crypto');
const QRCode = require('qrcode');
const CRC32 = require('crc-32');

const Util = require('./Util');
const ServerError = require('./ServerError');

const {
  WG_PATH,
  WG_HOST,
  WG_PORT,
  WG_MTU,
  WG_DEFAULT_DNS,
  WG_PERSISTENT_KEEPALIVE,
  WG_ROLE,
  WG_SUBNET,
  WG_HUBS,
  WG_PRE_UP,
  WG_POST_UP,
  WG_PRE_DOWN,
  WG_POST_DOWN,
  WG_ENABLE_EXPIRES_TIME,
  WG_ENABLE_ONE_TIME_LINKS,
  JC,
  JMIN,
  JMAX,
  S1,
  S2,
  H1,
  H2,
  H3,
  H4,
} = require('../config');

module.exports = class WireGuard {

  async __buildConfig() {
    this.__configPromise = Promise.resolve().then(async () => {
      if (!WG_HOST) {
        throw new Error('WG_HOST Environment Variable Not Set!');
      }

      debug('Loading configuration...');
      let config;
      try {
        config = await fs.readFile(path.join(WG_PATH, 'wg0.json'), 'utf8');
        config = JSON.parse(config);
        debug('Configuration loaded.');
      } catch (err) {
        const privateKey = await Util.exec('wg genkey');
        const publicKey = await Util.exec(`echo ${privateKey} | wg pubkey`, {
          log: 'echo ***hidden*** | wg pubkey',
        });
        const address = WG_SUBNET.replace('x', '1');

        config = {
          device: WG_DEVICE,
          hubs: [],
          peers: [],
        };

        if (WG_ROLE === 'node') {
          config.hubs.push({
            id: crypto.randomUUID(),
            name: 'wg-easy-hub',
            privateKey,
            publicKey,
            address,
            endpoint: `${WG_HOST}:${WG_PORT}`,
            subnet: WG_SUBNET,
            jc: JC,
            jmin: JMIN,
            jmax: JMAX,
            s1: S1,
            s2: S2,
            h1: H1,
            h2: H2,
            h3: H3,
            h4: H4,
            createdAt: new Date(),
            updatedAt: new Date(),
            enabled: true,
          });
        }

        for (const hubEndpoint of WG_HUBS) {
          // We need a way to get the public key of the other hubs.
          // This is a limitation of this approach. For now, we'll
          // just add them with a placeholder public key.
          config.hubs.push({
            id: crypto.randomUUID(),
            name: hubEndpoint,
            publicKey: 'PLACEHOLDER_PUBLIC_KEY',
            endpoint: hubEndpoint,
            createdAt: new Date(),
            updatedAt: new Date(),
            enabled: true,
          });
        }
        debug('Configuration generated.');
      }

      return config;
    });

    return this.__configPromise;
  }

  async getConfig() {
    if (!this.__configPromise) {
      const config = await this.__buildConfig();

      await this.__saveConfig(config);
      await Util.exec('wg-quick down wg0').catch(() => {});
      await Util.exec('wg-quick up wg0').catch((err) => {
        if (err && err.message && err.message.includes('Cannot find device "wg0"')) {
          throw new Error('WireGuard exited with the error: Cannot find device "wg0"\nThis usually means that your host\'s kernel does not support WireGuard!');
        }

        throw err;
      });
      // await Util.exec(`iptables -t nat -A POSTROUTING -s ${WG_DEFAULT_ADDRESS.replace('x', '0')}/24 -o ' + WG_DEVICE + ' -j MASQUERADE`);
      // await Util.exec('iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT');
      // await Util.exec('iptables -A FORWARD -i wg0 -j ACCEPT');
      // await Util.exec('iptables -A FORWARD -o wg0 -j ACCEPT');
      await this.__syncConfig();
    }

    return this.__configPromise;
  }

  async saveConfig() {
    const config = await this.getConfig();
    await this.__saveConfig(config);
    await this.__syncConfig();
  }

  async __saveConfig(config) {
    if (!config.hubs || config.hubs.length === 0) {
      return;
    }
    const self = config.hubs[0]; // Assuming self is the first hub
    const postUp = `iptables -t nat -A POSTROUTING -s ${self.subnet.replace('x', '0')}/24 -o ${config.device} -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport ${self.endpoint.split(':')[1]} -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;`;
    const postDown = `iptables -t nat -D POSTROUTING -s ${self.subnet.replace('x', '0')}/24 -o ${config.device} -j MASQUERADE; iptables -D INPUT -p udp -m udp --dport ${self.endpoint.split(':')[1]} -j ACCEPT; iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT;`;
    let result = `
# Note: Do not edit this file directly.
# Your changes will be overwritten!

# Self: ${self.name} (${self.id})
[Interface]
PrivateKey = ${self.privateKey}
Address = ${self.address}/24
ListenPort = ${self.endpoint.split(':')[1]}
PreUp = ${WG_PRE_UP}
PostUp = ${postUp}
PreDown = ${WG_PRE_DOWN}
PostDown = ${postDown}
Jc = ${self.jc}
Jmin = ${self.jmin}
Jmax = ${self.jmax}
S1 = ${self.s1}
S2 = ${self.s2}
H1 = ${self.h1}
H2 = ${self.h2}
H3 = ${self.h3}
H4 = ${self.h4}
`;

    // Add other hubs as peers
    for (const hub of config.hubs) {
      if (hub.id === self.id) continue; // Don't add self as a peer
      if (!hub.enabled) continue;

      result += `

# Hub: ${hub.name} (${hub.id})
[Peer]
PublicKey = ${hub.publicKey}
AllowedIPs = ${hub.subnet.replace('x', '0')}/24
Endpoint = ${hub.endpoint}`;
    }

    // Add peers as peers
    for (const peer of config.peers) {
      if (!peer.enabled) continue;

      result += `

# Peer: ${peer.name} (${peer.id})
[Peer]
PublicKey = ${peer.publicKey}
${peer.preSharedKey ? `PresharedKey = ${peer.preSharedKey}\n` : ''
}AllowedIPs = ${peer.address}/32`;
    }

    debug('Config saving...');
    await fs.writeFile(path.join(WG_PATH, 'wg0.json'), JSON.stringify(config, false, 2), {
      mode: 0o660,
    });
    await fs.writeFile(path.join(WG_PATH, 'wg0.conf'), result, {
      mode: 0o600,
    });
    debug('Config saved.');
  }

  async __syncConfig() {
    debug('Config syncing...');
    await Util.exec('wg syncconf wg0 <(wg-quick strip wg0)');
    debug('Config synced.');
  }

  async getPeers() {
    const config = await this.getConfig();
    if (!config.peers) {
      return [];
    }
    const peers = config.peers.map((peer) => ({
      ...peer,
      role: 'peer',
    }));

    // Loop WireGuard status
    const dump = await Util.exec('wg show wg0 dump', {
      log: false,
    });
    dump
      .trim()
      .split('\n')
      .slice(1)
      .forEach((line) => {
        const [
          publicKey,
          preSharedKey, // eslint-disable-line no-unused-vars
          endpoint, // eslint-disable-line no-unused-vars
          allowedIps, // eslint-disable-line no-unused-vars
          latestHandshakeAt,
          transferRx,
          transferTx,
          persistentKeepalive,
        ] = line.split('\t');

        const peer = peers.find((p) => p.publicKey === publicKey);
        if (!peer) return;

        peer.latestHandshakeAt = latestHandshakeAt === '0'
          ? null
          : new Date(Number(`${latestHandshakeAt}000`));
        // endpoint from dump is the connected endpoint, not the configured one.
        // peer.endpoint = endpoint === '(none)' ? null : endpoint;
        peer.transferRx = Number(transferRx);
        peer.transferTx = Number(transferTx);
        peer.persistentKeepalive = persistentKeepalive;
      });

    return peers;
  }

  async getHubs() {
    const config = await this.getConfig();
    return config.hubs;
  }

  async getPeer({ peerId }) {
    const config = await this.getConfig();
    const peer = config.peers.find((p) => p.id === peerId);
    if (!peer) {
      throw new ServerError(`Peer Not Found: ${peerId}`, 404);
    }

    return peer;
  }

  async getHub({ hubId }) {
    const config = await this.getConfig();
    const hub = config.hubs.find((h) => h.id === hubId);
    if (!hub) {
      throw new ServerError(`Hub Not Found: ${hubId}`, 404);
    }

    return hub;
  }

  async getPeerConfiguration({ peerId }) {
    const config = await this.getConfig();
    const peer = await this.getPeer({ peerId });

    let result = `
[Interface]
PrivateKey = ${peer.privateKey ? `${peer.privateKey}` : 'REPLACE_ME'}
Address = ${peer.address}/24
${WG_DEFAULT_DNS ? `DNS = ${WG_DEFAULT_DNS}\n` : ''}\
${WG_MTU ? `MTU = ${WG_MTU}\n` : ''}\
`;

    for (const hub of config.hubs) {
      const allowedIPs = peer.exitNode === hub.id ? '0.0.0.0/0, ::/0' : `${hub.subnet.replace('x', '0')}/24`;
      result += `

# Hub: ${hub.name}
[Peer]
PublicKey = ${hub.publicKey}
AllowedIPs = ${allowedIPs}
PersistentKeepalive = ${WG_PERSISTENT_KEEPALIVE}
Endpoint = ${hub.endpoint}`;
    }

    return result;
  }

  async getPeerQRCodeSVG({ peerId }) {
    const config = await this.getPeerConfiguration({ peerId });
    return QRCode.toString(config, {
      type: 'svg',
      width: 512,
    });
  }

  async createPeer({
    name, role, endpoint, expiredDate, exitNode,
  }) {
    if (!name) {
      throw new Error('Missing: Name');
    }

    const config = await this.getConfig();

    const privateKey = await Util.exec('wg genkey');
    const publicKey = await Util.exec(`echo ${privateKey} | wg pubkey`, {
      log: 'echo ***hidden*** | wg pubkey',
    });
    const preSharedKey = await Util.exec('wg genpsk');

    // Calculate next IP
    let address;
    for (let i = 2; i < 255; i++) {
      const peer = config.peers.find((p) => {
        return p.address === WG_SUBNET.replace('x', i);
      });

      if (!peer) {
        address = WG_SUBNET.replace('x', i);
        break;
      }
    }

    if (!address) {
      throw new Error('Maximum number of peers reached.');
    }

    const newPeer = {
      id: crypto.randomUUID(),
      name,
      role,
      address,
      endpoint,
      privateKey,
      publicKey,
      preSharedKey,
      exitNode,
      createdAt: new Date(),
      updatedAt: new Date(),
      expiredAt: null,
      enabled: true,
    };
    if (expiredDate) {
      newPeer.expiredAt = new Date(expiredDate);
      newPeer.expiredAt.setHours(23);
      newPeer.expiredAt.setMinutes(59);
      newPeer.expiredAt.setSeconds(59);
    }

    if (role === 'hub') {
      config.hubs.push(newPeer);
    } else {
      config.peers.push(newPeer);
    }

    await this.saveConfig();

    return newPeer;
  }

  async deletePeer({ peerId }) {
    const config = await this.getConfig();
    const peerIndex = config.peers.findIndex((p) => p.id === peerId);

    if (peerIndex !== -1) {
      config.peers.splice(peerIndex, 1);
      await this.saveConfig();
    }
  }

  async enablePeer({ peerId }) {
    const peer = await this.getPeer({ peerId });

    peer.enabled = true;
    peer.updatedAt = new Date();

    await this.saveConfig();
  }

  async updatePeerExitNode({ peerId, exitNode }) {
    const peer = await this.getPeer({ peerId });

    peer.exitNode = exitNode;
    peer.updatedAt = new Date();

    await this.saveConfig();
  }

  async generateOneTimeLink({ peerId }) {
    const peer = await this.getPeer({ peerId });
    const key = `${peerId}-${Math.floor(Math.random() * 1000)}`;
    peer.oneTimeLink = Math.abs(CRC32.str(key)).toString(16);
    peer.oneTimeLinkExpiresAt = new Date(Date.now() + 5 * 60 * 1000);
    peer.updatedAt = new Date();
    await this.saveConfig();
  }

  async eraseOneTimeLink({ peerId }) {
    const peer = await this.getPeer({ peerId });
    // peer.oneTimeLink = null;
    peer.oneTimeLinkExpiresAt = new Date(Date.now() + 10 * 1000);
    peer.updatedAt = new Date();
    await this.saveConfig();
  }

  async disablePeer({ peerId }) {
    const peer = await this.getPeer({ peerId });

    peer.enabled = false;
    peer.updatedAt = new Date();

    await this.saveConfig();
  }

  async updatePeerName({ peerId, name }) {
    const peer = await this.getPeer({ peerId });

    peer.name = name;
    peer.updatedAt = new Date();

    await this.saveConfig();
  }

  async updatePeerAddress({ peerId, address }) {
    const peer = await this.getPeer({ peerId });

    if (!Util.isValidIPv4(address)) {
      throw new ServerError(`Invalid Address: ${address}`, 400);
    }

    peer.address = address;
    peer.updatedAt = new Date();

    await this.saveConfig();
  }

  async updatePeerExpireDate({ peerId, expireDate }) {
    const peer = await this.getPeer({ peerId });

    if (expireDate) {
      peer.expiredAt = new Date(expireDate);
      peer.expiredAt.setHours(23);
      peer.expiredAt.setMinutes(59);
      peer.expiredAt.setSeconds(59);
    } else {
      peer.expiredAt = null;
    }
    peer.updatedAt = new Date();

    await this.saveConfig();
  }

  async __reloadConfig() {
    await this.__buildConfig();
    await this.__syncConfig();
  }

  async restoreConfiguration(config) {
    debug('Starting configuration restore process.');
    const _config = JSON.parse(config);
    await this.__saveConfig(_config);
    await this.__reloadConfig();
    debug('Configuration restore process completed.');
  }

  async backupConfiguration() {
    debug('Starting configuration backup.');
    const config = await this.getConfig();
    const backup = JSON.stringify(config, null, 2);
    debug('Configuration backup completed.');
    return backup;
  }

  // Shutdown wireguard
  async Shutdown() {
    await Util.exec('wg-quick down wg0').catch(() => {});
  }

  async cronJobEveryMinute() {
    const config = await this.getConfig();
    let needSaveConfig = false;
    // Expires Feature
    if (WG_ENABLE_EXPIRES_TIME === 'true') {
      for (const peer of config.peers) {
        if (peer.enabled !== true) continue;
        if (peer.expiredAt !== null && new Date() > new Date(peer.expiredAt)) {
          debug(`Peer ${peer.id} expired.`);
          needSaveConfig = true;
          peer.enabled = false;
          peer.updatedAt = new Date();
        }
      }
    }
    // One Time Link Feature
    if (WG_ENABLE_ONE_TIME_LINKS === 'true') {
      for (const peer of config.peers) {
        if (peer.oneTimeLink !== null && new Date() > new Date(peer.oneTimeLinkExpiresAt)) {
          debug(`Peer ${peer.id} One Time Link expired.`);
          needSaveConfig = true;
          peer.oneTimeLink = null;
          peer.oneTimeLinkExpiresAt = null;
          peer.updatedAt = new Date();
        }
      }
    }
    if (needSaveConfig) {
      await this.saveConfig();
    }
  }

  async getMetrics() {
    const peers = await this.getPeers();
    let wireguardPeerCount = 0;
    let wireguardEnabledPeersCount = 0;
    let wireguardConnectedPeersCount = 0;
    let wireguardSentBytes = '';
    let wireguardReceivedBytes = '';
    let wireguardLatestHandshakeSeconds = '';
    for (const peer of peers) {
      wireguardPeerCount++;
      if (peer.enabled === true) {
        wireguardEnabledPeersCount++;
      }
      if (peer.endpoint !== null) {
        wireguardConnectedPeersCount++;
      }
      wireguardSentBytes += `wireguard_sent_bytes{interface="wg0",enabled="${peer.enabled}",address="${peer.address}",name="${peer.name}"} ${Number(peer.transferTx)}\n`;
      wireguardReceivedBytes += `wireguard_received_bytes{interface="wg0",enabled="${peer.enabled}",address="${peer.address}",name="${peer.name}"} ${Number(peer.transferRx)}\n`;
      wireguardLatestHandshakeSeconds += `wireguard_latest_handshake_seconds{interface="wg0",enabled="${peer.enabled}",address="${peer.address}",name="${peer.name}"} ${peer.latestHandshakeAt ? (new Date().getTime() - new Date(peer.latestHandshakeAt).getTime()) / 1000 : 0}\n`;
    }

    let returnText = '# HELP wg-easy and wireguard metrics\n';

    returnText += '\n# HELP wireguard_configured_peers\n';
    returnText += '# TYPE wireguard_configured_peers gauge\n';
    returnText += `wireguard_configured_peers{interface="wg0"} ${Number(wireguardPeerCount)}\n`;

    returnText += '\n# HELP wireguard_enabled_peers\n';
    returnText += '# TYPE wireguard_enabled_peers gauge\n';
    returnText += `wireguard_enabled_peers{interface="wg0"} ${Number(wireguardEnabledPeersCount)}\n`;

    returnText += '\n# HELP wireguard_connected_peers\n';
    returnText += '# TYPE wireguard_connected_peers gauge\n';
    returnText += `wireguard_connected_peers{interface="wg0"} ${Number(wireguardConnectedPeersCount)}\n`;

    returnText += '\n# HELP wireguard_sent_bytes Bytes sent to the peer\n';
    returnText += '# TYPE wireguard_sent_bytes counter\n';
    returnText += `${wireguardSentBytes}`;

    returnText += '\n# HELP wireguard_received_bytes Bytes received from the peer\n';
    returnText += '# TYPE wireguard_received_bytes counter\n';
    returnText += `${wireguardReceivedBytes}`;

    returnText += '\n# HELP wireguard_latest_handshake_seconds UNIX timestamp seconds of the last handshake\n';
    returnText += '# TYPE wireguard_latest_handshake_seconds gauge\n';
    returnText += `${wireguardLatestHandshakeSeconds}`;

    return returnText;
  }

  async getMetricsJSON() {
    const peers = await this.getPeers();
    let wireguardPeerCount = 0;
    let wireguardEnabledPeersCount = 0;
    let wireguardConnectedPeersCount = 0;
    for (const peer of peers) {
      wireguardPeerCount++;
      if (peer.enabled === true) {
        wireguardEnabledPeersCount++;
      }
      if (peer.endpoint !== null) {
        wireguardConnectedPeersCount++;
      }
    }
    return {
      wireguard_configured_peers: Number(wireguardPeerCount),
      wireguard_enabled_peers: Number(wireguardEnabledPeersCount),
      wireguard_connected_peers: Number(wireguardConnectedPeersCount),
    };
  }

  async updateSettings({ subnet, port }) {
    const config = await this.getConfig();
    const self = config.hubs[0];
    self.subnet = subnet;
    self.endpoint = `${WG_HOST}:${port}`;
    self.address = subnet.replace('x', '1');
    await this.__saveConfig(config);
  }

  async restart() {
    await Util.exec('wg-quick down wg0').catch(() => {});
    await Util.exec('wg-quick up wg0').catch((err) => {
      if (err && err.message && err.message.includes('Cannot find device "wg0"')) {
        throw new Error('WireGuard exited with the error: Cannot find device "wg0"\\nThis usually means that your host\'s kernel does not support WireGuard!');
      }
      throw err;
    });
  }
};
