'use strict';

const fs = require('node:fs/promises');
const path = require('path');
const debug = require('debug')('WireGuard');
const crypto = require('node:crypto');
const QRCode = require('qrcode');
const CRC32 = require('crc-32');

const Util = require('./Util');
const ServerError = require('./ServerError');

const {
  WG_PATH,
  WG_HOST,
  WG_PORT,
  WG_CONFIG_PORT,
  WG_MTU,
  WG_DEFAULT_DNS,
  WG_DEFAULT_ADDRESS,
  WG_PERSISTENT_KEEPALIVE,
  WG_ALLOWED_IPS,
  WG_PRE_UP,
  WG_POST_UP,
  WG_PRE_DOWN,
  WG_POST_DOWN,
  WG_ENABLE_EXPIRES_TIME,
  WG_ENABLE_ONE_TIME_LINKS,
  JC,
  JMIN,
  JMAX,
  S1,
  S2,
  H1,
  H2,
  H3,
  H4,
} = require('../config');

module.exports = class WireGuard {

  async __buildConfig() {
    this.__configPromise = Promise.resolve().then(async () => {
      if (!WG_HOST) {
        throw new Error('WG_HOST Environment Variable Not Set!');
      }

      debug('Loading configuration...');
      let config;
      try {
        config = await fs.readFile(path.join(WG_PATH, 'wg0.json'), 'utf8');
        config = JSON.parse(config);
        debug('Configuration loaded.');
      } catch (err) {
        const privateKey = await Util.exec('wg genkey');
        const publicKey = await Util.exec(`echo ${privateKey} | wg pubkey`, {
          log: 'echo ***hidden*** | wg pubkey',
        });
        const address = WG_DEFAULT_ADDRESS.replace('x', '1');

        config = {
          server: {
            privateKey,
            publicKey,
            address,
            jc: JC,
            jmin: JMIN,
            jmax: JMAX,
            s1: S1,
            s2: S2,
            h1: H1,
            h2: H2,
            h3: H3,
            h4: H4,
          },
          peers: {},
        };
        debug('Configuration generated.');
      }

      // Migration from old format
      if (config.clients && !config.peers) {
        debug('Migrating clients to peers...');
        config.peers = {};
        for (const [clientId, client] of Object.entries(config.clients)) {
          config.peers[clientId] = {
            ...client,
            type: 'client',
          };
        }
        delete config.clients;
        debug('Migration complete.');
      }

      return config;
    });

    return this.__configPromise;
  }

  async getConfig() {
    if (!this.__configPromise) {
      const config = await this.__buildConfig();

      await this.__saveConfig(config);
      await Util.exec('wg-quick down wg0').catch(() => {});
      await Util.exec('wg-quick up wg0').catch((err) => {
        if (err && err.message && err.message.includes('Cannot find device "wg0"')) {
          throw new Error('WireGuard exited with the error: Cannot find device "wg0"\nThis usually means that your host\'s kernel does not support WireGuard!');
        }

        throw err;
      });
      await this.__syncConfig();
    }

    return this.__configPromise;
  }

  async saveConfig() {
    const config = await this.getConfig();
    await this.__saveConfig(config);
    await this.__syncConfig();
  }

  async __saveConfig(config) {
    let result = `
# Note: Do not edit this file directly.
# Your changes will be overwritten!

# Server
[Interface]
PrivateKey = ${config.server.privateKey}
Address = ${config.server.address}/24
ListenPort = ${WG_PORT}
PreUp = ${WG_PRE_UP}
PostUp = ${WG_POST_UP}
PreDown = ${WG_PRE_DOWN}
PostDown = ${WG_POST_DOWN}
Jc = ${config.server.jc}
Jmin = ${config.server.jmin}
Jmax = ${config.server.jmax}
S1 = ${config.server.s1}
S2 = ${config.server.s2}
H1 = ${config.server.h1}
H2 = ${config.server.h2}
H3 = ${config.server.h3}
H4 = ${config.server.h4}
`;

    for (const [peerId, peer] of Object.entries(config.peers)) {
      if (!peer.enabled) continue;

      if (peer.type === 'client') {
        result += `

# Client: ${peer.name} (${peerId})
[Peer]
PublicKey = ${peer.publicKey}
${peer.preSharedKey ? `PresharedKey = ${peer.preSharedKey}\n` : ''
}AllowedIPs = ${peer.address}/32`;
      } else if (peer.type === 'server') {
        result += `

# Peer: ${peer.name} (${peerId})
[Peer]
PublicKey = ${peer.publicKey}
${peer.preSharedKey ? `PresharedKey = ${peer.preSharedKey}\n` : ''
}${peer.allowedIPs ? `AllowedIPs = ${peer.allowedIPs}\n` : ''
}${peer.endpoint ? `Endpoint = ${peer.endpoint}\n` : ''
}${peer.persistentKeepalive ? `PersistentKeepalive = ${peer.persistentKeepalive}\n` : ''}`;
      }
    }

    debug('Config saving...');
    await fs.writeFile(path.join(WG_PATH, 'wg0.json'), JSON.stringify(config, false, 2), {
      mode: 0o660,
    });
    await fs.writeFile(path.join(WG_PATH, 'wg0.conf'), result, {
      mode: 0o600,
    });
    debug('Config saved.');
  }

  async __syncConfig() {
    debug('Config syncing...');
    await Util.exec('wg syncconf wg0 <(wg-quick strip wg0)');
    debug('Config synced.');
  }

  async getPeers() {
    const config = await this.getConfig();
    const peers = Object.entries(config.peers).map(([peerId, peer]) => ({
      id: peerId,
      type: peer.type,
      name: peer.name,
      enabled: peer.enabled,
      address: peer.address,
      publicKey: peer.publicKey,
      createdAt: new Date(peer.createdAt),
      updatedAt: new Date(peer.updatedAt),
      expiredAt: peer.expiredAt !== null
        ? new Date(peer.expiredAt)
        : null,
      allowedIPs: peer.allowedIPs,
      oneTimeLink: peer.oneTimeLink ?? null,
      oneTimeLinkExpiresAt: peer.oneTimeLinkExpiresAt ?? null,
      downloadableConfig: 'privateKey' in peer,
      persistentKeepalive: peer.persistentKeepalive,
      latestHandshakeAt: null,
      transferRx: null,
      transferTx: null,
      endpoint: peer.endpoint,
    }));

    // Loop WireGuard status
    const dump = await Util.exec('wg show wg0 dump', {
      log: false,
    });
    dump
      .trim()
      .split('\n')
      .slice(1)
      .forEach((line) => {
        const [
          publicKey,
          preSharedKey, // eslint-disable-line no-unused-vars
          endpoint,
          allowedIps, // eslint-disable-line no-unused-vars
          latestHandshakeAt,
          transferRx,
          transferTx,
          persistentKeepalive,
        ] = line.split('\t');

        const peer = peers.find((p) => p.publicKey === publicKey);
        if (!peer) return;

        const newLatestHandshakeAt = latestHandshakeAt === '0'
          ? null
          : new Date(Number(`${latestHandshakeAt}000`));

        if (newLatestHandshakeAt && peer.latestHandshakeAt !== newLatestHandshakeAt) {
            debug(`Peer ${peer.name} (${peer.id}) connected from ${endpoint}`);
        } else if (!newLatestHandshakeAt && peer.latestHandshakeAt) {
            debug(`Peer ${peer.name} (${peer.id}) disconnected`);
        }

        peer.latestHandshakeAt = newLatestHandshakeAt;

        if (endpoint !== '(none)') {
          peer.endpoint = endpoint;
        }
        peer.transferRx = Number(transferRx);
        peer.transferTx = Number(transferTx);
        peer.persistentKeepalive = persistentKeepalive;
      });

    return peers;
  }

  async getPeer({ peerId }) {
    const config = await this.getConfig();
    const peer = config.peers[peerId];
    if (!peer) {
      throw new ServerError(`Peer Not Found: ${peerId}`, 404);
    }

    return peer;
  }

  async getClientConfiguration({ clientId }) {
    const config = await this.getConfig();
    const client = await this.getPeer({ peerId: clientId });

    return `
[Interface]
PrivateKey = ${client.privateKey ? `${client.privateKey}` : 'REPLACE_ME'}
Address = ${client.address}/24
${WG_DEFAULT_DNS ? `DNS = ${WG_DEFAULT_DNS}\n` : ''}\
${WG_MTU ? `MTU = ${WG_MTU}\n` : ''}\
Jc = ${config.server.jc}
Jmin = ${config.server.jmin}
Jmax = ${config.server.jmax}
S1 = ${config.server.s1}
S2 = ${config.server.s2}
H1 = ${config.server.h1}
H2 = ${config.server.h2}
H3 = ${config.server.h3}
H4 = ${config.server.h4}

[Peer]
PublicKey = ${config.server.publicKey}
${client.preSharedKey ? `PresharedKey = ${client.preSharedKey}\n` : ''
}AllowedIPs = ${WG_ALLOWED_IPS}
PersistentKeepalive = ${WG_PERSISTENT_KEEPALIVE}
Endpoint = ${WG_HOST}:${WG_CONFIG_PORT}`;
  }

  async getClientQRCodeSVG({ clientId }) {
    const config = await this.getClientConfiguration({ clientId });
    return QRCode.toString(config, {
      type: 'svg',
      width: 512,
    });
  }

  async createPeer(peerData) {
    debug('Creating peer with data: %o', peerData);
    const { type, name } = peerData;
    if (!name) {
      throw new Error('Missing: Name');
    }

    const config = await this.getConfig();
    const id = crypto.randomUUID();

    if (type === 'client') {
      const { expiredDate } = peerData;
      const privateKey = await Util.exec('wg genkey');
      const publicKey = await Util.exec(`echo ${privateKey} | wg pubkey`, {
        log: 'echo ***hidden*** | wg pubkey',
      });
      const preSharedKey = await Util.exec('wg genpsk');

      // Calculate next IP
      let address;
      for (let i = 2; i < 255; i++) {
        const ip = WG_DEFAULT_ADDRESS.replace('x', i);
        const peer = Object.values(config.peers).find((p) => p.address === ip);
        if (!peer) {
          address = ip;
          break;
        }
      }

      if (!address) {
        throw new Error('Maximum number of clients reached.');
      }

      const client = {
        id,
        type: 'client',
        name,
        address,
        privateKey,
        publicKey,
        preSharedKey,
        createdAt: new Date(),
        updatedAt: new Date(),
        expiredAt: null,
        enabled: true,
      };
      if (expiredDate) {
        client.expiredAt = new Date(expiredDate);
        client.expiredAt.setHours(23);
        client.expiredAt.setMinutes(59);
        client.expiredAt.setSeconds(59);
      }
      config.peers[id] = client;
      await this.saveConfig();
      return client;
    } else if (type === 'server') {
      const { publicKey, preSharedKey, endpoint, allowedIPs, persistentKeepalive } = peerData;
      if (!publicKey || !allowedIPs) {
        throw new Error('Missing required fields for server peer: publicKey, allowedIPs');
      }

      const serverPeer = {
        id,
        type: 'server',
        name,
        publicKey,
        preSharedKey,
        endpoint,
        allowedIPs,
        persistentKeepalive,
        createdAt: new Date(),
        updatedAt: new Date(),
        enabled: true,
      };
      config.peers[id] = serverPeer;
      await this.saveConfig();
      return serverPeer;
    } else {
      throw new Error(`Invalid peer type: ${type}`);
    }
  }

  async deletePeer({ peerId }) {
    const config = await this.getConfig();

    if (config.peers[peerId]) {
      delete config.peers[peerId];
      await this.saveConfig();
    }
  }

  async enablePeer({ peerId }) {
    const peer = await this.getPeer({ peerId });

    peer.enabled = true;
    peer.updatedAt = new Date();

    await this.saveConfig();
  }

  async generateOneTimeLink({ clientId }) {
    const client = await this.getPeer({ peerId: clientId });
    if (client.type !== 'client') {
      throw new ServerError('One-time links are only available for clients.', 400);
    }
    const key = `${clientId}-${Math.floor(Math.random() * 1000)}`;
    client.oneTimeLink = Math.abs(CRC32.str(key)).toString(16);
    client.oneTimeLinkExpiresAt = new Date(Date.now() + 5 * 60 * 1000);
    client.updatedAt = new Date();
    await this.saveConfig();
  }

  async eraseOneTimeLink({ clientId }) {
    const client = await this.getPeer({ peerId: clientId });
    if (client.type !== 'client') {
      return;
    }
    // client.oneTimeLink = null;
    client.oneTimeLinkExpiresAt = new Date(Date.now() + 10 * 1000);
    client.updatedAt = new Date();
    await this.saveConfig();
  }

  async disablePeer({ peerId }) {
    const peer = await this.getPeer({ peerId });

    peer.enabled = false;
    peer.updatedAt = new Date();

    await this.saveConfig();
  }

  async updatePeerName({ peerId, name }) {
    const peer = await this.getPeer({ peerId });

    peer.name = name;
    peer.updatedAt = new Date();

    await this.saveConfig();
  }

  async updatePeerAddress({ peerId, address }) {
    const peer = await this.getPeer({ peerId });
    if (peer.type !== 'client') {
      throw new ServerError('Address can only be updated for clients.', 400);
    }

    if (!Util.isValidIPv4(address)) {
      throw new ServerError(`Invalid Address: ${address}`, 400);
    }

    peer.address = address;
    peer.updatedAt = new Date();

    await this.saveConfig();
  }

  async updatePeerExpireDate({ peerId, expireDate }) {
    const peer = await this.getPeer({ peerId });
    if (peer.type !== 'client') {
      throw new ServerError('Expiration date can only be updated for clients.', 400);
    }

    if (expireDate) {
      peer.expiredAt = new Date(expireDate);
      peer.expiredAt.setHours(23);
      peer.expiredAt.setMinutes(59);
      peer.expiredAt.setSeconds(59);
    } else {
      peer.expiredAt = null;
    }
    peer.updatedAt = new Date();

    await this.saveConfig();
  }

  async __reloadConfig() {
    await this.__buildConfig();
    await this.__syncConfig();
  }

  async restoreConfiguration(config) {
    debug('Starting configuration restore process.');
    const _config = JSON.parse(config);
    await this.__saveConfig(_config);
    await this.__reloadConfig();
    debug('Configuration restore process completed.');
  }

  async backupConfiguration() {
    debug('Starting configuration backup.');
    const config = await this.getConfig();
    const backup = JSON.stringify(config, null, 2);
    debug('Configuration backup completed.');
    return backup;
  }

  // Shutdown wireguard
  async Shutdown() {
    await Util.exec('wg-quick down wg0').catch(() => {});
  }

  async cronJobEveryMinute() {
    const config = await this.getConfig();
    let needSaveConfig = false;
    // Expires Feature
    if (WG_ENABLE_EXPIRES_TIME === 'true') {
      for (const peer of Object.values(config.peers)) {
        if (peer.type !== 'client' || peer.enabled !== true) continue;
        if (peer.expiredAt !== null && new Date() > new Date(peer.expiredAt)) {
          debug(`Client ${peer.id} expired.`);
          needSaveConfig = true;
          peer.enabled = false;
          peer.updatedAt = new Date();
        }
      }
    }
    // One Time Link Feature
    if (WG_ENABLE_ONE_TIME_LINKS === 'true') {
      for (const peer of Object.values(config.peers)) {
        if (peer.type !== 'client') continue;
        if (peer.oneTimeLink !== null && new Date() > new Date(peer.oneTimeLinkExpiresAt)) {
          debug(`Client ${peer.id} One Time Link expired.`);
          needSaveConfig = true;
          peer.oneTimeLink = null;
          peer.oneTimeLinkExpiresAt = null;
          peer.updatedAt = new Date();
        }
      }
    }
    if (needSaveConfig) {
      await this.saveConfig();
    }
  }

  async getMetrics() {
    const peers = await this.getPeers();
    const clients = peers.filter((p) => p.type === 'client');
    let wireguardPeerCount = 0;
    let wireguardEnabledPeersCount = 0;
    let wireguardConnectedPeersCount = 0;
    let wireguardSentBytes = '';
    let wireguardReceivedBytes = '';
    let wireguardLatestHandshakeSeconds = '';
    for (const client of Object.values(clients)) {
      wireguardPeerCount++;
      if (client.enabled === true) {
        wireguardEnabledPeersCount++;
      }
      if (client.endpoint !== null) {
        wireguardConnectedPeersCount++;
      }
      wireguardSentBytes += `wireguard_sent_bytes{interface="wg0",enabled="${client.enabled}",address="${client.address}",name="${client.name}"} ${Number(client.transferTx)}\n`;
      wireguardReceivedBytes += `wireguard_received_bytes{interface="wg0",enabled="${client.enabled}",address="${client.address}",name="${client.name}"} ${Number(client.transferRx)}\n`;
      wireguardLatestHandshakeSeconds += `wireguard_latest_handshake_seconds{interface="wg0",enabled="${client.enabled}",address="${client.address}",name="${client.name}"} ${client.latestHandshakeAt ? (new Date().getTime() - new Date(client.latestHandshakeAt).getTime()) / 1000 : 0}\n`;
    }

    let returnText = '# HELP wg-easy and wireguard metrics\n';

    returnText += '\n# HELP wireguard_configured_peers\n';
    returnText += '# TYPE wireguard_configured_peers gauge\n';
    returnText += `wireguard_configured_peers{interface="wg0"} ${Number(wireguardPeerCount)}\n`;

    returnText += '\n# HELP wireguard_enabled_peers\n';
    returnText += '# TYPE wireguard_enabled_peers gauge\n';
    returnText += `wireguard_enabled_peers{interface="wg0"} ${Number(wireguardEnabledPeersCount)}\n`;

    returnText += '\n# HELP wireguard_connected_peers\n';
    returnText += '# TYPE wireguard_connected_peers gauge\n';
    returnText += `wireguard_connected_peers{interface="wg0"} ${Number(wireguardConnectedPeersCount)}\n`;

    returnText += '\n# HELP wireguard_sent_bytes Bytes sent to the peer\n';
    returnText += '# TYPE wireguard_sent_bytes counter\n';
    returnText += `${wireguardSentBytes}`;

    returnText += '\n# HELP wireguard_received_bytes Bytes received from the peer\n';
    returnText += '# TYPE wireguard_received_bytes counter\n';
    returnText += `${wireguardReceivedBytes}`;

    returnText += '\n# HELP wireguard_latest_handshake_seconds UNIX timestamp seconds of the last handshake\n';
    returnText += '# TYPE wireguard_latest_handshake_seconds gauge\n';
    returnText += `${wireguardLatestHandshakeSeconds}`;

    return returnText;
  }

  async getMetricsJSON() {
    const peers = await this.getPeers();
    const clients = peers.filter((p) => p.type === 'client');
    let wireguardPeerCount = 0;
    let wireguardEnabledPeersCount = 0;
    let wireguardConnectedPeersCount = 0;
    for (const client of Object.values(clients)) {
      wireguardPeerCount++;
      if (client.enabled === true) {
        wireguardEnabledPeersCount++;
      }
      if (client.endpoint !== null) {
        wireguardConnectedPeersCount++;
      }
    }
    return {
      wireguard_configured_peers: Number(wireguardPeerCount),
      wireguard_enabled_peers: Number(wireguardEnabledPeersCount),
      wireguard_connected_peers: Number(wireguardConnectedPeersCount),
    };
  }

};
