'use strict';

const fs = require('node:fs/promises');
const path = require('path');
const debug = require('debug')('WireGuard');
const crypto = require('node:crypto');
const QRCode = require('qrcode');
const CRC32 = require('crc-32');

const Util = require('./Util');
const ServerError = require('./ServerError');

const {
  WG_PATH,
  WG_HOST,
  WG_PORT,
  WG_CONFIG_PORT,
  WG_MTU,
  WG_DEFAULT_DNS,
  WG_DEFAULT_ADDRESS,
  WG_PERSISTENT_KEEPALIVE,
  WG_ALLOWED_IPS,
  WG_PRE_UP,
  WG_POST_UP,
  WG_PRE_DOWN,
  WG_POST_DOWN,
  WG_ENABLE_EXPIRES_TIME,
  WG_ENABLE_ONE_TIME_LINKS,
  JC,
  JMIN,
  JMAX,
  S1,
  S2,
  H1,
  H2,
  H3,
  H4,
} = require('../config');

module.exports = class WireGuard {

  async __buildConfig() {
    this.__configPromise = Promise.resolve().then(async () => {
      if (!WG_HOST) {
        throw new Error('WG_HOST Environment Variable Not Set!');
      }

      debug('Loading configuration...');
      let config;
      try {
        config = await fs.readFile(path.join(WG_PATH, 'wg0.json'), 'utf8');
        config = JSON.parse(config);
        debug('Configuration loaded.');
      } catch (err) {
        const privateKey = await Util.exec('wg genkey');
        const publicKey = await Util.exec(`echo ${privateKey} | wg pubkey`, {
          log: 'echo ***hidden*** | wg pubkey',
        });
        const address = WG_DEFAULT_ADDRESS.replace('x', '1');

        config = {
          interfaces: {
            wg0: {
              privateKey,
              publicKey,
              address,
              jc: JC,
              jmin: JMIN,
              jmax: JMAX,
              s1: S1,
              s2: S2,
              h1: H1,
              h2: H2,
              h3: H3,
              h4: H4,
              peers: {},
            },
          },
          clients: {},
          servers: {},
        };
        debug('Configuration generated.');
      }

      return config;
    });

    return this.__configPromise;
  }

  async getConfig() {
    if (!this.__configPromise) {
      const config = await this.__buildConfig();

      for (const interfaceName of Object.keys(config.interfaces)) {
        await this.__saveConfig(config, interfaceName);
        await Util.exec(`wg-quick down ${interfaceName}`).catch(() => {});
        await Util.exec(`wg-quick up ${interfaceName}`).catch((err) => {
          if (err && err.message && err.message.includes(`Cannot find device "${interfaceName}"`)) {
            throw new Error(`WireGuard exited with the error: Cannot find device "${interfaceName}"\nThis usually means that your host's kernel does not support WireGuard!`);
          }
          throw err;
        });
        await this.__syncConfig(interfaceName);
      }
    }
    return this.__configPromise;
  }

  async saveConfig(interfaceName = 'wg0') {
    const config = await this.getConfig();
    await this.__saveConfig(config, interfaceName);
    await this.__syncConfig(interfaceName);
  }

  async __saveConfig(config, interfaceName) {
    const interfaceConfig = config.interfaces[interfaceName];
    if (!interfaceConfig) {
      throw new Error(`Interface ${interfaceName} not found in config.`);
    }

    let result = `
# Note: Do not edit this file directly.
# Your changes will be overwritten!

# Interface: ${interfaceName}
[Interface]
PrivateKey = ${interfaceConfig.privateKey}
Address = ${interfaceConfig.address}/24
ListenPort = ${interfaceConfig.listenPort || WG_PORT}
PreUp = ${interfaceConfig.preUp || ''}
PostUp = ${interfaceConfig.postUp || ''}
PreDown = ${interfaceConfig.preDown || ''}
PostDown = ${interfaceConfig.postDown || ''}
Jc = ${interfaceConfig.jc}
Jmin = ${interfaceConfig.jmin}
Jmax = ${interfaceConfig.jmax}
S1 = ${interfaceConfig.s1}
S2 = ${interfaceConfig.s2}
H1 = ${interfaceConfig.h1}
H2 = ${interfaceConfig.h2}
H3 = ${interfaceConfig.h3}
H4 = ${interfaceConfig.h4}
`;

    for (const [peerId, peer] of Object.entries(interfaceConfig.peers)) {
      if (!peer.enabled) continue;

      result += `

# Peer: ${peer.name} (${peerId})
[Peer]
PublicKey = ${peer.publicKey}
${peer.presharedKey ? `PresharedKey = ${peer.presharedKey}\n` : ''
}${peer.endpoint ? `Endpoint = ${peer.endpoint}\n` : ''
}${peer.persistentKeepalive ? `PersistentKeepalive = ${peer.persistentKeepalive}\n` : ''
}AllowedIPs = ${peer.allowedIPs}`;
    }

    debug(`Config saving for ${interfaceName}...`);
    await fs.writeFile(path.join(WG_PATH, 'wg0.json'), JSON.stringify(config, false, 2), {
      mode: 0o660,
    });
    await fs.writeFile(path.join(WG_PATH, `${interfaceName}.conf`), result, {
      mode: 0o600,
    });
    debug(`Config saved for ${interfaceName}.`);
  }

  async __syncConfig(interfaceName) {
    debug(`Config syncing for ${interfaceName}...`);
    await Util.exec(`wg syncconf ${interfaceName} <(wg-quick strip ${interfaceName})`);
    debug(`Config synced for ${interfaceName}.`);
  }

  async getClients() {
    const config = await this.getConfig();
    const clients = Object.entries(config.interfaces.wg0.peers).map(([clientId, client]) => ({
      id: clientId,
      name: client.name,
      enabled: client.enabled,
      address: client.address,
      publicKey: client.publicKey,
      createdAt: new Date(client.createdAt),
      updatedAt: new Date(client.updatedAt),
      expiredAt: client.expiredAt !== null
        ? new Date(client.expiredAt)
        : null,
      allowedIPs: client.allowedIPs,
      oneTimeLink: client.oneTimeLink ?? null,
      oneTimeLinkExpiresAt: client.oneTimeLinkExpiresAt ?? null,
      downloadableConfig: 'privateKey' in client,
      persistentKeepalive: null,
      latestHandshakeAt: null,
      transferRx: null,
      transferTx: null,
      endpoint: null,
    }));

    // Loop WireGuard status
    const dump = await Util.exec('wg show wg0 dump', {
      log: false,
    });
    dump
      .trim()
      .split('\n')
      .slice(1)
      .forEach((line) => {
        const [
          publicKey,
          preSharedKey, // eslint-disable-line no-unused-vars
          endpoint, // eslint-disable-line no-unused-vars
          allowedIps, // eslint-disable-line no-unused-vars
          latestHandshakeAt,
          transferRx,
          transferTx,
          persistentKeepalive,
        ] = line.split('\t');

        const client = clients.find((client) => client.publicKey === publicKey);
        if (!client) return;

        client.latestHandshakeAt = latestHandshakeAt === '0'
          ? null
          : new Date(Number(`${latestHandshakeAt}000`));
        client.endpoint = endpoint === '(none)' ? null : endpoint;
        client.transferRx = Number(transferRx);
        client.transferTx = Number(transferTx);
        client.persistentKeepalive = persistentKeepalive;
      });

    return clients;
  }

  async getServers() {
    const config = await this.getConfig();
    const servers = [];
    for (const interfaceName in config.interfaces) {
      if (interfaceName === 'wg0') continue;
      const interfaceConfig = config.interfaces[interfaceName];
      const peer = Object.values(interfaceConfig.peers)[0];
      let status = 'down';
      try {
        await Util.exec(`wg show ${interfaceName}`);
        status = 'up';
      } catch (error) {
        // ignore
      }
      servers.push({
        name: interfaceName,
        ...interfaceConfig,
        ...peer,
        status,
      });
    }
    return servers;
  }

  async getClient({ clientId }) {
    const config = await this.getConfig();
    const client = config.interfaces.wg0.peers[clientId];
    if (!client) {
      throw new ServerError(`Client Not Found: ${clientId}`, 404);
    }

    return client;
  }

  async getClientConfiguration({ clientId }) {
    const config = await this.getConfig();
    const client = await this.getClient({ clientId });
    const wg0 = config.interfaces.wg0;

    return `
[Interface]
PrivateKey = ${client.privateKey ? `${client.privateKey}` : 'REPLACE_ME'}
Address = ${client.address}/24
${WG_DEFAULT_DNS ? `DNS = ${WG_DEFAULT_DNS}\n` : ''}\
${WG_MTU ? `MTU = ${WG_MTU}\n` : ''}\
Jc = ${wg0.jc}
Jmin = ${wg0.jmin}
Jmax = ${wg0.jmax}
S1 = ${wg0.s1}
S2 = ${wg0.s2}
H1 = ${wg0.h1}
H2 = ${wg0.h2}
H3 = ${wg0.h3}
H4 = ${wg0.h4}

[Peer]
PublicKey = ${wg0.publicKey}
${client.preSharedKey ? `PresharedKey = ${client.preSharedKey}\n` : ''
}AllowedIPs = ${WG_ALLOWED_IPS}
PersistentKeepalive = ${WG_PERSISTENT_KEEPALIVE}
Endpoint = ${WG_HOST}:${WG_CONFIG_PORT}`;
  }

  async getClientQRCodeSVG({ clientId }) {
    const config = await this.getClientConfiguration({ clientId });
    return QRCode.toString(config, {
      type: 'svg',
      width: 512,
    });
  }

  async createClient({ name, expiredDate }) {
    if (!name) {
      throw new Error('Missing: Name');
    }

    const config = await this.getConfig();

    const privateKey = await Util.exec('wg genkey');
    const publicKey = await Util.exec(`echo ${privateKey} | wg pubkey`, {
      log: 'echo ***hidden*** | wg pubkey',
    });
    const preSharedKey = await Util.exec('wg genpsk');

    // Calculate next IP
    let address;
    for (let i = 2; i < 255; i++) {
      const client = Object.values(config.interfaces.wg0.peers).find((client) => {
        return client.address === WG_DEFAULT_ADDRESS.replace('x', i);
      });

      if (!client) {
        address = WG_DEFAULT_ADDRESS.replace('x', i);
        break;
      }
    }

    if (!address) {
      throw new Error('Maximum number of clients reached.');
    }
    // Create Client
    const id = crypto.randomUUID();
    const client = {
      id,
      name,
      address,
      privateKey,
      publicKey,
      preSharedKey,

      createdAt: new Date(),
      updatedAt: new Date(),
      expiredAt: null,
      enabled: true,
    };
    if (expiredDate) {
      client.expiredAt = new Date(expiredDate);
      client.expiredAt.setHours(23);
      client.expiredAt.setMinutes(59);
      client.expiredAt.setSeconds(59);
    }
    config.interfaces.wg0.peers[id] = client;

    await this.saveConfig('wg0');

    return client;
  }

  async createServer({ privateKey, address, dns, mtu, jc, jmin, jmax, s1, s2, h1, h2, h3, h4, publicKey, presharedKey, allowedIPs, endpoint, persistentKeepalive }) {
    debug('Creating server with params:', { privateKey, address, dns, mtu, jc, jmin, jmax, s1, s2, h1, h2, h3, h4, publicKey, presharedKey, allowedIPs, endpoint, persistentKeepalive });
    const config = await this.getConfig();
    const interfaceName = await this.getNextInterfaceName();

    const newInterface = {
      privateKey,
      address,
      dns,
      mtu,
      jc,
      jmin,
      jmax,
      s1,
      s2,
      h1,
      h2,
      h3,
      h4,
      peers: {
        [crypto.randomUUID()]: {
          name: 'server',
          publicKey,
          presharedKey,
          allowedIPs,
          endpoint,
          persistentKeepalive,
          enabled: true,
        },
      },
    };

    config.interfaces[interfaceName] = newInterface;

    await this.__saveConfig(config, interfaceName);
    await Util.exec(`wg-quick up ${interfaceName}`).catch((err) => {
      if (err && err.message && err.message.includes(`Cannot find device "${interfaceName}"`)) {
        throw new Error(`WireGuard exited with the error: Cannot find device "${interfaceName}"\nThis usually means that your host's kernel does not support WireGuard!`);
      }
      throw err;
    });
    await this.__syncConfig(interfaceName);

    return newInterface;
  }

  async getNextInterfaceName() {
    const config = await this.getConfig();
    let i = 0;
    while (true) {
      const interfaceName = `wg${i}`;
      if (!config.interfaces[interfaceName]) {
        return interfaceName;
      }
      i++;
    }
  }

  async deleteServer({ interfaceName }) {
    const config = await this.getConfig();
    if (config.interfaces[interfaceName]) {
      await Util.exec(`wg-quick down ${interfaceName}`).catch(() => {});
      await fs.unlink(path.join(WG_PATH, `${interfaceName}.conf`)).catch(() => {});
      delete config.interfaces[interfaceName];
      await fs.writeFile(path.join(WG_PATH, 'wg0.json'), JSON.stringify(config, false, 2), {
        mode: 0o660,
      });
    }
  }

  async updateServer({ interfaceName, privateKey, address, dns, mtu, jc, jmin, jmax, s1, s2, h1, h2, h3, h4, publicKey, presharedKey, allowedIPs, endpoint, persistentKeepalive }) {
    const config = await this.getConfig();
    if (config.interfaces[interfaceName]) {
      await Util.exec(`wg-quick down ${interfaceName}`).catch(() => {});

      const updatedInterface = {
        privateKey,
        address,
        dns,
        mtu,
        jc,
        jmin,
        jmax,
        s1,
        s2,
        h1,
        h2,
        h3,
        h4,
        peers: {
          [crypto.randomUUID()]: {
            name: 'server',
            publicKey,
            presharedKey,
            allowedIPs,
            endpoint,
            persistentKeepalive,
            enabled: true,
          },
        },
      };

      config.interfaces[interfaceName] = updatedInterface;

      await this.__saveConfig(config, interfaceName);
      await Util.exec(`wg-quick up ${interfaceName}`).catch((err) => {
        if (err && err.message && err.message.includes(`Cannot find device "${interfaceName}"`)) {
          throw new Error(`WireGuard exited with the error: Cannot find device "${interfaceName}"\nThis usually means that your host's kernel does not support WireGuard!`);
        }
        throw err;
      });
      await this.__syncConfig(interfaceName);
    }
  }

  async deleteClient({ clientId }) {
    const config = await this.getConfig();

    if (config.interfaces.wg0.peers[clientId]) {
      delete config.interfaces.wg0.peers[clientId];
      await this.saveConfig('wg0');
    }
  }

  async enableClient({ clientId }) {
    const client = await this.getClient({ clientId });

    client.enabled = true;
    client.updatedAt = new Date();

    await this.saveConfig('wg0');
  }

  async generateOneTimeLink({ clientId }) {
    const client = await this.getClient({ clientId });
    const key = `${clientId}-${Math.floor(Math.random() * 1000)}`;
    client.oneTimeLink = Math.abs(CRC32.str(key)).toString(16);
    client.oneTimeLinkExpiresAt = new Date(Date.now() + 5 * 60 * 1000);
    client.updatedAt = new Date();
    await this.saveConfig();
  }

  async eraseOneTimeLink({ clientId }) {
    const client = await this.getClient({ clientId });
    // client.oneTimeLink = null;
    client.oneTimeLinkExpiresAt = new Date(Date.now() + 10 * 1000);
    client.updatedAt = new Date();
    await this.saveConfig();
  }

  async disableClient({ clientId }) {
    const client = await this.getClient({ clientId });

    client.enabled = false;
    client.updatedAt = new Date();

    await this.saveConfig('wg0');
  }

  async updateClientName({ clientId, name }) {
    const client = await this.getClient({ clientId });

    client.name = name;
    client.updatedAt = new Date();

    await this.saveConfig('wg0');
  }

  async updateClientAddress({ clientId, address }) {
    const client = await this.getClient({ clientId });

    if (!Util.isValidIPv4(address)) {
      throw new ServerError(`Invalid Address: ${address}`, 400);
    }

    client.address = address;
    client.updatedAt = new Date();

    await this.saveConfig('wg0');
  }

  async updateClientExpireDate({ clientId, expireDate }) {
    const client = await this.getClient({ clientId });

    if (expireDate) {
      client.expiredAt = new Date(expireDate);
      client.expiredAt.setHours(23);
      client.expiredAt.setMinutes(59);
      client.expiredAt.setSeconds(59);
    } else {
      client.expiredAt = null;
    }
    client.updatedAt = new Date();

    await this.saveConfig('wg0');
  }

  async __reloadConfig() {
    await this.__buildConfig();
    await this.__syncConfig();
  }

  async restoreConfiguration(config) {
    debug('Starting configuration restore process.');
    const _config = JSON.parse(config);
    await this.__saveConfig(_config);
    await this.__reloadConfig();
    debug('Configuration restore process completed.');
  }

  async backupConfiguration() {
    debug('Starting configuration backup.');
    const config = await this.getConfig();
    const backup = JSON.stringify(config, null, 2);
    debug('Configuration backup completed.');
    return backup;
  }

  // Shutdown wireguard
  async Shutdown() {
    await Util.exec('wg-quick down wg0').catch(() => {});
  }

  async cronJobEveryMinute() {
    const config = await this.getConfig();
    let needSaveConfig = false;
    // Expires Feature
    if (WG_ENABLE_EXPIRES_TIME === 'true') {
      for (const client of Object.values(config.interfaces.wg0.peers)) {
        if (client.enabled !== true) continue;
        if (client.expiredAt !== null && new Date() > new Date(client.expiredAt)) {
          debug(`Client ${client.id} expired.`);
          needSaveConfig = true;
          client.enabled = false;
          client.updatedAt = new Date();
        }
      }
    }
    // One Time Link Feature
    if (WG_ENABLE_ONE_TIME_LINKS === 'true') {
      for (const client of Object.values(config.interfaces.wg0.peers)) {
        if (client.oneTimeLink !== null && new Date() > new Date(client.oneTimeLinkExpiresAt)) {
          debug(`Client ${client.id} One Time Link expired.`);
          needSaveConfig = true;
          client.oneTimeLink = null;
          client.oneTimeLinkExpiresAt = null;
          client.updatedAt = new Date();
        }
      }
    }
    if (needSaveConfig) {
      await this.saveConfig('wg0');
    }
  }

  async getMetrics() {
    const clients = await this.getClients();
    let wireguardPeerCount = 0;
    let wireguardEnabledPeersCount = 0;
    let wireguardConnectedPeersCount = 0;
    let wireguardSentBytes = '';
    let wireguardReceivedBytes = '';
    let wireguardLatestHandshakeSeconds = '';
    for (const client of Object.values(clients)) {
      wireguardPeerCount++;
      if (client.enabled === true) {
        wireguardEnabledPeersCount++;
      }
      if (client.endpoint !== null) {
        wireguardConnectedPeersCount++;
      }
      wireguardSentBytes += `wireguard_sent_bytes{interface="wg0",enabled="${client.enabled}",address="${client.address}",name="${client.name}"} ${Number(client.transferTx)}\n`;
      wireguardReceivedBytes += `wireguard_received_bytes{interface="wg0",enabled="${client.enabled}",address="${client.address}",name="${client.name}"} ${Number(client.transferRx)}\n`;
      wireguardLatestHandshakeSeconds += `wireguard_latest_handshake_seconds{interface="wg0",enabled="${client.enabled}",address="${client.address}",name="${client.name}"} ${client.latestHandshakeAt ? (new Date().getTime() - new Date(client.latestHandshakeAt).getTime()) / 1000 : 0}\n`;
    }

    let returnText = '# HELP wg-easy and wireguard metrics\n';

    returnText += '\n# HELP wireguard_configured_peers\n';
    returnText += '# TYPE wireguard_configured_peers gauge\n';
    returnText += `wireguard_configured_peers{interface="wg0"} ${Number(wireguardPeerCount)}\n`;

    returnText += '\n# HELP wireguard_enabled_peers\n';
    returnText += '# TYPE wireguard_enabled_peers gauge\n';
    returnText += `wireguard_enabled_peers{interface="wg0"} ${Number(wireguardEnabledPeersCount)}\n`;

    returnText += '\n# HELP wireguard_connected_peers\n';
    returnText += '# TYPE wireguard_connected_peers gauge\n';
    returnText += `wireguard_connected_peers{interface="wg0"} ${Number(wireguardConnectedPeersCount)}\n`;

    returnText += '\n# HELP wireguard_sent_bytes Bytes sent to the peer\n';
    returnText += '# TYPE wireguard_sent_bytes counter\n';
    returnText += `${wireguardSentBytes}`;

    returnText += '\n# HELP wireguard_received_bytes Bytes received from the peer\n';
    returnText += '# TYPE wireguard_received_bytes counter\n';
    returnText += `${wireguardReceivedBytes}`;

    returnText += '\n# HELP wireguard_latest_handshake_seconds UNIX timestamp seconds of the last handshake\n';
    returnText += '# TYPE wireguard_latest_handshake_seconds gauge\n';
    returnText += `${wireguardLatestHandshakeSeconds}`;

    return returnText;
  }

  async getMetricsJSON() {
    const clients = await this.getClients();
    let wireguardPeerCount = 0;
    let wireguardEnabledPeersCount = 0;
    let wireguardConnectedPeersCount = 0;
    for (const client of Object.values(clients)) {
      wireguardPeerCount++;
      if (client.enabled === true) {
        wireguardEnabledPeersCount++;
      }
      if (client.endpoint !== null) {
        wireguardConnectedPeersCount++;
      }
    }
    return {
      wireguard_configured_peers: Number(wireguardPeerCount),
      wireguard_enabled_peers: Number(wireguardEnabledPeersCount),
      wireguard_connected_peers: Number(wireguardConnectedPeersCount),
    };
  }

};
