const assert = require('assert');

async function saveConfig(config) {
  let result = `
# Note: Do not edit this file directly.
# Your changes will be overwritten!

# Server
[Interface]
PrivateKey = ${config.server.privateKey}
Address = ${config.server.address}/24
ListenPort = 51820
PreUp =
PostUp =
PreDown =
PostDown =
Jc = 0
Jmin = 0
Jmax = 0
S1 = 0
S2 = 0
H1 = 0
H2 = 0
H3 = 0
H4 = 0
`;

  for (const [clientId, client] of Object.entries(config.clients)) {
    if (!client.enabled) continue;

    result += `

# Client: ${client.name} (${clientId})
[Peer]
PublicKey = ${client.publicKey}
${client.preSharedKey ? `PresharedKey = ${client.preSharedKey}\n` : ''
}AllowedIPs = ${client.address}/32`;
  }

  for (const [serverId, server] of Object.entries(config.servers)) {
    if (!server.enabled) continue;

    result += `

# Server: ${server.name} (${serverId})
[Peer]
PublicKey = ${server.publicKey}
${server.preSharedKey ? `PresharedKey = ${server.preSharedKey}\n` : ''
}AllowedIPs = ${server.allowedIps}
Endpoint = ${server.endpoint}
PersistentKeepalive = 25`;
  }
  return result;
}

async function test() {
  console.log('Starting test...');

  const config = {
    server: {
      privateKey: 'test-server-private-key',
      address: '10.0.0.1',
    },
    clients: {},
    servers: {},
  };

  // Test client creation
  console.log('Testing client creation...');
  const clientId = 'test-client-id';
  config.clients[clientId] = {
    id: clientId,
    name: 'test-client',
    enabled: true,
    address: '10.0.0.2',
    publicKey: 'test-client-public-key',
    preSharedKey: 'test-client-preshared-key',
  };
  let confContent = await saveConfig(config);
  assert(confContent.includes('# Client: test-client (test-client-id)'), 'Client section should exist');
  assert(confContent.includes('PublicKey = test-client-public-key'), 'Client public key should exist');
  assert(confContent.includes('AllowedIPs = 10.0.0.2/32'), 'Client AllowedIPs should be correct');
  console.log('Client creation test passed.');

  // Test server peer creation
  console.log('Testing server peer creation...');
  const serverId = 'test-server-id';
  config.servers[serverId] = {
    id: serverId,
    name: 'test-server',
    enabled: true,
    publicKey: 'test-server-public-key',
    preSharedKey: 'test-server-preshared-key',
    endpoint: 'test-server-endpoint',
    allowedIps: '10.1.0.0/24',
  };
  confContent = await saveConfig(config);
  assert(confContent.includes('# Server: test-server (test-server-id)'), 'Server section should exist');
  assert(confContent.includes('PublicKey = test-server-public-key'), 'Server public key should exist');
  assert(confContent.includes('AllowedIPs = 10.1.0.0/24'), 'Server AllowedIPs should be correct');
  assert(confContent.includes('Endpoint = test-server-endpoint'), 'Server endpoint should be correct');
  console.log('Server peer creation test passed.');

  // Test client deletion
  console.log('Testing client deletion...');
  delete config.clients[clientId];
  confContent = await saveConfig(config);
  assert(!confContent.includes('# Client: test-client (test-client-id)'), 'Client section should not exist');
  console.log('Client deletion test passed.');

  // Test server peer deletion
  console.log('Testing server peer deletion...');
  delete config.servers[serverId];
  confContent = await saveConfig(config);
  assert(!confContent.includes('# Server: test-server (test-server-id)'), 'Server section should not exist');
  console.log('Server peer deletion test passed.');


  console.log('All tests passed!');
}

test().catch(err => {
  console.error("Test failed:", err);
  process.exit(1);
});
